/**
 * Monaco editor themes adapted from monaco-themes package.
 * Token scopes: Monokai (dark) and Tomorrow (light) — proven TextMate coverage.
 * UI colors and syntax palette: remapped to Mahogany / Linen warm tones
 * and Norton (NC-inspired blue/cyan) tones.
 */
import type * as Monaco from "monaco-editor";

// ── Mahogany (dark) — Monokai scopes, warm brown palette ─────────────────────

export const MONACO_THEME_MAHOGANY: Monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { background: "120806", token: "" },

    // ── Comments ──────────────────────────────────────────────────────────────
    { foreground: "5C4035", token: "comment", fontStyle: "italic" },
    { foreground: "5C4035", token: "meta.diff" },
    { foreground: "5C4035", token: "meta.diff.header" },

    // ── Strings ───────────────────────────────────────────────────────────────
    { foreground: "C89848", token: "string" },
    { foreground: "C89848", token: "markup.changed" },
    { foreground: "C89848", token: "entity.name.filename.find-in-files" },

    // ── Constants / numbers ───────────────────────────────────────────────────
    { foreground: "D4B060", token: "constant.numeric" },
    { foreground: "D4B060", token: "constant.language" },
    { foreground: "D4B060", token: "constant.character" },
    { foreground: "D4B060", token: "constant.other" },
    { foreground: "D4B060A0", token: "constant.numeric.line-number.find-in-files - match" },
    // Monarch token name
    { foreground: "D4B060", token: "number" },
    { foreground: "D4B060", token: "number.float" },
    { foreground: "D4B060", token: "number.hex" },
    { foreground: "C89848", token: "regexp" },

    // ── Keywords / storage ────────────────────────────────────────────────────
    { foreground: "E08848", token: "keyword" },
    { foreground: "E08848", token: "storage" },

    // ── Types / support — muted warm cream (replaces blue) ───────────────────
    { foreground: "C0A880", token: "storage.type", fontStyle: "italic" },
    { foreground: "B8A890", token: "support.function" },
    { foreground: "B8A890", token: "support.constant" },
    { foreground: "B8A890", token: "support.type", fontStyle: "italic" },
    { foreground: "B8A890", token: "support.class", fontStyle: "italic" },
    // Monarch type tokens
    { foreground: "C0A880", token: "type" },
    { foreground: "C0A880", token: "type.identifier" },
    { foreground: "C0A880", token: "class" },

    // ── Functions / identifiers ───────────────────────────────────────────────
    { foreground: "E8D8B0", token: "entity.name.class", fontStyle: "underline" },
    { foreground: "E8D8B0", token: "entity.other.inherited-class", fontStyle: "italic underline" },
    { foreground: "E8D8B0", token: "entity.name.function" },
    // Monarch function tokens
    { foreground: "E8D8B0", token: "function" },
    { foreground: "E8D8B0", token: "function.name" },

    // ── Parameters / variables ────────────────────────────────────────────────
    { foreground: "C0A870", token: "variable.parameter", fontStyle: "italic" },
    { foreground: "CEC0A2", token: "variable" },
    { foreground: "CEC0A2", token: "identifier" },

    // ── XML / HTML (TextMate scopes) ──────────────────────────────────────────
    { foreground: "E08848", token: "entity.name.tag" },
    { foreground: "C89848", token: "entity.other.attribute-name" },
    { foreground: "C08840", token: "meta.tag" },
    // XML / HTML (Monarch token names)
    { foreground: "E08848", token: "tag" },
    { foreground: "C89848", token: "attribute.name" },
    { foreground: "C09848", token: "attribute.value" },
    { foreground: "8A7060", token: "metatag" },
    { foreground: "8A7060", token: "metatag.content", fontStyle: "italic" },

    // ── CSS / SCSS (Monarch) ──────────────────────────────────────────────────
    { foreground: "E08848", token: "selector" },
    { foreground: "E08848", token: "selector.tag" },
    { foreground: "D4A060", token: "selector.class" },
    { foreground: "D4A060", token: "selector.id" },
    { foreground: "C89848", token: "property.css" },
    { foreground: "C89848", token: "property" },
    { foreground: "D4B060", token: "unit" },
    { foreground: "B8A890", token: "pseudo" },
    { foreground: "E08848", token: "important" },

    // ── INI / TOML (Monarch) ──────────────────────────────────────────────────
    { foreground: "E08848", token: "section" },
    { foreground: "CEC0A2", token: "key" },
    { foreground: "C89848", token: "value" },

    // ── Operators / delimiters ────────────────────────────────────────────────
    { foreground: "C07848", token: "operator" },
    { foreground: "7A6050", token: "delimiter" },
    { foreground: "7A6050", token: "delimiter.bracket" },
    { foreground: "7A6050", token: "delimiter.parenthesis" },
    { foreground: "7A6050", token: "delimiter.curly" },
    { foreground: "7A6050", token: "delimiter.square" },
    { foreground: "7A6050", token: "delimiter.array" },

    // ── JSON ──────────────────────────────────────────────────────────────────
    { foreground: "B8B0A0", token: "meta.structure.dictionary.json string.quoted.double.json" },

    // ── Markdown ──────────────────────────────────────────────────────────────
    { foreground: "E8D8B0", token: "markup.heading" },
    { foreground: "E08848", token: "markup.bold", fontStyle: "bold" },
    { foreground: "C89848", token: "markup.italic", fontStyle: "italic" },
    { foreground: "B8A890", token: "markup.underline.link" },
    { foreground: "C89848", token: "markup.inline.raw" },

    // ── Diff ──────────────────────────────────────────────────────────────────
    { foreground: "A04040", token: "markup.deleted" },
    { foreground: "90A840", token: "markup.inserted" },

    // ── Invalid ───────────────────────────────────────────────────────────────
    { foreground: "CEC0A2", background: "803030", token: "invalid" },
    { foreground: "CEC0A2", background: "604880", token: "invalid.deprecated" },
  ],
  colors: {
    "editor.background": "#120806",
    "editor.foreground": "#CEC0A2",
    "editorLineNumber.foreground": "#3A2018",
    "editorLineNumber.activeForeground": "#7A5840",
    "editor.lineHighlightBackground": "#1E0E0A",
    "editor.lineHighlightBorder": "#00000000",
    "editor.selectionBackground": "#3D201880",
    "editor.inactiveSelectionBackground": "#2C140850",
    "editor.selectionHighlightBackground": "#3D201840",
    "editor.wordHighlightBackground": "#3D201840",
    "editor.wordHighlightStrongBackground": "#4A281840",
    "editorCursor.foreground": "#C09168",
    "editorCursor.background": "#120806",
    "editorBracketMatch.background": "#3D201860",
    "editorBracketMatch.border": "#875A3550",
    "editorIndentGuide.background1": "#251008",
    "editorIndentGuide.activeBackground1": "#3D2018",
    "editorRuler.foreground": "#251008",
    "editorWhitespace.foreground": "#2C1408",
    "editorWidget.background": "#1A0D08",
    "editorWidget.border": "#3C1D10",
    "editorWidget.foreground": "#CEC0A2",
    "editorSuggestWidget.background": "#1A0D08",
    "editorSuggestWidget.border": "#3C1D10",
    "editorSuggestWidget.foreground": "#CEC0A2",
    "editorSuggestWidget.selectedBackground": "#3D2018",
    "editorSuggestWidget.highlightForeground": "#E08848",
    "editorHoverWidget.background": "#1A0D08",
    "editorHoverWidget.border": "#3C1D10",
    "editorHoverWidget.foreground": "#CEC0A2",
    "editorGutter.background": "#120806",
    "editorGutter.addedBackground": "#2C5020",
    "editorGutter.modifiedBackground": "#5A3810",
    "editorGutter.deletedBackground": "#501818",
    "scrollbar.shadow": "#00000060",
    "scrollbarSlider.background": "#3D201850",
    "scrollbarSlider.hoverBackground": "#5A302080",
    "scrollbarSlider.activeBackground": "#875A3590",
    "editor.findMatchBackground": "#875A3560",
    "editor.findMatchHighlightBackground": "#3D201840",
    "editor.findMatchBorder": "#C0906060",
    "editorSelectionHighlightBorder": "#3D201850",
    "input.background": "#170C07",
    "input.border": "#3C1D10",
    "input.foreground": "#CEC0A2",
    "input.placeholderForeground": "#5A4035",
    "dropdown.background": "#1A0D08",
    "dropdown.border": "#3C1D10",
    "dropdown.foreground": "#CEC0A2",
    "list.hoverBackground": "#2C1408",
    "list.activeSelectionBackground": "#3D2018",
    "list.activeSelectionForeground": "#CEC0A2",
    "list.inactiveSelectionBackground": "#2C1408",
    "list.highlightForeground": "#E08848",
    "focusBorder": "#875A3570",
  },
};

// ── Linen (light) — Tomorrow scopes, warm linen palette ──────────────────────

export const MONACO_THEME_LINEN: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { background: "C8BCA8", token: "" },
    // Comments — muted warm grey-brown, italic
    { foreground: "9A8A7A", token: "comment", fontStyle: "italic" },
    // Misc operators / embedded
    { foreground: "6A5040", token: "keyword.operator.class" },
    { foreground: "6A5040", token: "constant.other" },
    { foreground: "6A5040", token: "source.php.embedded.line" },
    // Variables / tags / attributes — dark warm red-brown
    { foreground: "7A2818", token: "variable" },
    { foreground: "7A2818", token: "support.other.variable" },
    { foreground: "7A2818", token: "string.other.link" },
    { foreground: "7A2818", token: "string.regexp" },
    { foreground: "7A2818", token: "entity.name.tag" },
    { foreground: "7A2818", token: "entity.other.attribute-name" },
    { foreground: "7A2818", token: "meta.tag" },
    { foreground: "7A2818", token: "declaration.tag" },
    { foreground: "7A2818", token: "markup.deleted.git_gutter" },
    // Constants / numbers / units — dark amber
    { foreground: "7A4010", token: "constant.numeric" },
    { foreground: "7A4010", token: "constant.language" },
    { foreground: "7A4010", token: "support.constant" },
    { foreground: "7A4010", token: "constant.character" },
    { foreground: "7A4010", token: "variable.parameter" },
    { foreground: "7A4010", token: "punctuation.section.embedded" },
    { foreground: "7A4010", token: "keyword.other.unit" },
    // Classes / types — dark warm brown
    { foreground: "5A4018", token: "entity.name.class" },
    { foreground: "5A4018", token: "entity.name.type.class" },
    { foreground: "5A4018", token: "support.type" },
    { foreground: "5A4018", token: "support.class" },
    // Strings — dark amber-brown
    { foreground: "6A4020", token: "string" },
    { foreground: "6A4020", token: "constant.other.symbol" },
    { foreground: "6A4020", token: "entity.other.inherited-class" },
    { foreground: "6A4020", token: "markup.heading" },
    { foreground: "6A4020", token: "markup.inserted.git_gutter" },
    // Operators — medium warm brown
    { foreground: "7A5838", token: "keyword.operator" },
    { foreground: "7A5838", token: "constant.other.color" },
    // Functions / methods — dark warm (replaces blue)
    { foreground: "4A3828", token: "entity.name.function" },
    { foreground: "4A3828", token: "meta.function-call" },
    { foreground: "4A3828", token: "support.function" },
    { foreground: "4A3828", token: "keyword.other.special-method" },
    { foreground: "4A3828", token: "meta.block-level" },
    { foreground: "4A3828", token: "markup.changed.git_gutter" },
    // Keywords / storage — darkest warm (replaces purple)
    { foreground: "6B2818", token: "keyword" },
    { foreground: "6B2818", token: "storage" },
    { foreground: "6B2818", token: "storage.type" },
    // Diff / special
    { foreground: "1A100A", background: "7A3030", token: "invalid" },
    { foreground: "1A100A", background: "504038", token: "meta.separator" },
    { foreground: "1A100A", background: "6B2818", token: "invalid.deprecated" },
    { foreground: "EEE8D8", token: "markup.inserted.diff" },
    { foreground: "EEE8D8", token: "markup.deleted.diff" },
    { foreground: "EEE8D8", token: "meta.diff.header.to-file" },
    { foreground: "EEE8D8", token: "meta.diff.header.from-file" },
    { background: "5A7030", token: "markup.inserted.diff" },
    { background: "5A7030", token: "meta.diff.header.to-file" },
    { background: "7A3030", token: "markup.deleted.diff" },
    { background: "7A3030", token: "meta.diff.header.from-file" },
    { foreground: "EEE8D8", background: "5A4838", token: "meta.diff.header.from-file" },
    { foreground: "EEE8D8", background: "5A4838", token: "meta.diff.header.to-file" },
    { foreground: "7A5838", token: "meta.diff.range", fontStyle: "italic" },

    // ── Constants / numbers (Monarch) ─────────────────────────────────────────
    { foreground: "7A4010", token: "number" },
    { foreground: "7A4010", token: "number.float" },
    { foreground: "7A4010", token: "number.hex" },
    { foreground: "6A4020", token: "regexp" },

    // ── Keywords / storage (Monarch) ──────────────────────────────────────────
    { foreground: "6B2818", token: "keyword.control" },
    { foreground: "6B2818", token: "keyword.other" },

    // ── Types / support (Monarch) — replaces inherited blue ───────────────────
    { foreground: "5A4018", token: "type" },
    { foreground: "5A4018", token: "type.identifier" },
    { foreground: "5A4018", token: "class" },

    // ── Functions / identifiers (Monarch) ─────────────────────────────────────
    { foreground: "4A3828", token: "function" },
    { foreground: "4A3828", token: "function.name" },
    { foreground: "2A1808", token: "identifier" },

    // ── XML / HTML (Monarch) ──────────────────────────────────────────────────
    { foreground: "7A2818", token: "tag" },
    { foreground: "7A3010", token: "attribute.name" },
    { foreground: "6A4020", token: "attribute.value" },
    { foreground: "9A8878", token: "metatag" },
    { foreground: "9A8878", token: "metatag.content", fontStyle: "italic" },

    // ── CSS / SCSS (Monarch) ──────────────────────────────────────────────────
    { foreground: "7A2818", token: "selector" },
    { foreground: "7A2818", token: "selector.tag" },
    { foreground: "6A3010", token: "selector.class" },
    { foreground: "6A3010", token: "selector.id" },
    { foreground: "6A4020", token: "property.css" },
    { foreground: "6A4020", token: "property" },
    { foreground: "7A4010", token: "unit" },
    { foreground: "5A4030", token: "pseudo" },
    { foreground: "7A2818", token: "important" },

    // ── INI / TOML (Monarch) ──────────────────────────────────────────────────
    { foreground: "7A2818", token: "section" },
    { foreground: "2A1808", token: "key" },
    { foreground: "6A4020", token: "value" },

    // ── Operators / delimiters (Monarch) ──────────────────────────────────────
    { foreground: "7A5838", token: "operator" },
    { foreground: "8A7060", token: "delimiter" },
    { foreground: "8A7060", token: "delimiter.bracket" },
    { foreground: "8A7060", token: "delimiter.parenthesis" },
    { foreground: "8A7060", token: "delimiter.curly" },
    { foreground: "8A7060", token: "delimiter.square" },
    { foreground: "8A7060", token: "delimiter.array" },
  ],
  colors: {
    "editor.background": "#C8BCA8",
    "editor.foreground": "#1A100A",
    "editorLineNumber.foreground": "#A09080",
    "editorLineNumber.activeForeground": "#5A4A3A",
    "editor.lineHighlightBackground": "#BEB29E",
    "editor.lineHighlightBorder": "#00000000",
    "editor.selectionBackground": "#A09080AA",
    "editor.inactiveSelectionBackground": "#B0A49060",
    "editor.selectionHighlightBackground": "#A0908050",
    "editor.wordHighlightBackground": "#A0908050",
    "editor.wordHighlightStrongBackground": "#906E5050",
    "editorCursor.foreground": "#3A2618",
    "editorCursor.background": "#C8BCA8",
    "editorBracketMatch.background": "#9A8A7060",
    "editorBracketMatch.border": "#7A6E5A70",
    "editorIndentGuide.background1": "#B8AC98",
    "editorIndentGuide.activeBackground1": "#9A8A78",
    "editorRuler.foreground": "#B8AC98",
    "editorWhitespace.foreground": "#B0A490",
    "editorWidget.background": "#CBBFAB",
    "editorWidget.border": "#8A7A6A",
    "editorWidget.foreground": "#1A100A",
    "editorSuggestWidget.background": "#CBBFAB",
    "editorSuggestWidget.border": "#8A7A6A",
    "editorSuggestWidget.foreground": "#1A100A",
    "editorSuggestWidget.selectedBackground": "#B0A490",
    "editorSuggestWidget.highlightForeground": "#6B2818",
    "editorHoverWidget.background": "#CBBFAB",
    "editorHoverWidget.border": "#8A7A6A",
    "editorHoverWidget.foreground": "#1A100A",
    "editorGutter.background": "#C8BCA8",
    "editorGutter.addedBackground": "#507040",
    "editorGutter.modifiedBackground": "#906030",
    "editorGutter.deletedBackground": "#803030",
    "scrollbar.shadow": "#00000020",
    "scrollbarSlider.background": "#8A7A6A50",
    "scrollbarSlider.hoverBackground": "#6A5A4A80",
    "scrollbarSlider.activeBackground": "#4A3A2A90",
    "editor.findMatchBackground": "#7A5A3060",
    "editor.findMatchHighlightBackground": "#A08A6040",
    "editor.findMatchBorder": "#7A4A2080",
    "editorSelectionHighlightBorder": "#A0908060",
    "input.background": "#BDAF99",
    "input.border": "#8A7A6A",
    "input.foreground": "#1A100A",
    "input.placeholderForeground": "#8A7A6A",
    "dropdown.background": "#CBBFAB",
    "dropdown.border": "#8A7A6A",
    "dropdown.foreground": "#1A100A",
    "list.hoverBackground": "#BEB29E",
    "list.activeSelectionBackground": "#A09080",
    "list.activeSelectionForeground": "#1A100A",
    "list.inactiveSelectionBackground": "#B0A490",
    "list.highlightForeground": "#6B2818",
    "focusBorder": "#7A6A5A70",
  },
};

// ── Norton Dark — NC-inspired deep navy + cyan palette ───────────────────────
//
// Colour philosophy: faithful to Norton Commander 5 blue-panel aesthetic.
// Background: deep navy  |  Text: cyan-white  |  Accents: bright cyan + yellow
// Syntax: keywords=yellow, strings=green, numbers=magenta, functions=cyan

export const MONACO_THEME_NORTON_DARK: Monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { background: "0D0D6A", token: "" },

    // ── Comments ──────────────────────────────────────────────────────────────
    { foreground: "7AAFDD", token: "comment", fontStyle: "italic" },
    { foreground: "334499", token: "meta.diff" },
    { foreground: "334499", token: "meta.diff.header" },

    // ── Strings ───────────────────────────────────────────────────────────────
    { foreground: "44DD88", token: "string" },
    { foreground: "44DD88", token: "markup.changed" },
    { foreground: "44DD88", token: "entity.name.filename.find-in-files" },
    { foreground: "44DD88", token: "regexp" },

    // ── Constants / numbers ───────────────────────────────────────────────────
    { foreground: "FF77CC", token: "constant.numeric" },
    { foreground: "FF77CC", token: "constant.language" },
    { foreground: "FF77CC", token: "constant.character" },
    { foreground: "FF77CC", token: "constant.other" },
    { foreground: "FF77CC", token: "number" },
    { foreground: "FF77CC", token: "number.float" },
    { foreground: "FF77CC", token: "number.hex" },

    // ── Keywords / storage ────────────────────────────────────────────────────
    { foreground: "FFEE44", token: "keyword" },
    { foreground: "FFEE44", token: "storage" },

    // ── Types / support ───────────────────────────────────────────────────────
    { foreground: "88BBFF", token: "storage.type", fontStyle: "italic" },
    { foreground: "88BBFF", token: "support.function" },
    { foreground: "88BBFF", token: "support.constant" },
    { foreground: "88BBFF", token: "support.type", fontStyle: "italic" },
    { foreground: "88BBFF", token: "support.class", fontStyle: "italic" },
    { foreground: "88BBFF", token: "type" },
    { foreground: "88BBFF", token: "type.identifier" },
    { foreground: "88BBFF", token: "class" },

    // ── Functions / identifiers ───────────────────────────────────────────────
    { foreground: "44EEFF", token: "entity.name.class", fontStyle: "underline" },
    { foreground: "44EEFF", token: "entity.other.inherited-class", fontStyle: "italic underline" },
    { foreground: "44EEFF", token: "entity.name.function" },
    { foreground: "44EEFF", token: "function" },
    { foreground: "44EEFF", token: "function.name" },

    // ── Parameters / variables ────────────────────────────────────────────────
    { foreground: "AACCFF", token: "variable.parameter", fontStyle: "italic" },
    { foreground: "BBEEFF", token: "variable" },
    { foreground: "BBEEFF", token: "identifier" },

    // ── XML / HTML ────────────────────────────────────────────────────────────
    { foreground: "FF9944", token: "entity.name.tag" },
    { foreground: "FFCC44", token: "entity.other.attribute-name" },
    { foreground: "DD8833", token: "meta.tag" },
    { foreground: "FF9944", token: "tag" },
    { foreground: "FFCC44", token: "attribute.name" },
    { foreground: "FFEE66", token: "attribute.value" },
    { foreground: "445588", token: "metatag" },
    { foreground: "445588", token: "metatag.content", fontStyle: "italic" },

    // ── CSS / SCSS ────────────────────────────────────────────────────────────
    { foreground: "FF9944", token: "selector" },
    { foreground: "FF9944", token: "selector.tag" },
    { foreground: "FFCC44", token: "selector.class" },
    { foreground: "FFCC44", token: "selector.id" },
    { foreground: "44DD88", token: "property.css" },
    { foreground: "44DD88", token: "property" },
    { foreground: "FF77CC", token: "unit" },
    { foreground: "88BBFF", token: "pseudo" },
    { foreground: "FF5533", token: "important" },

    // ── INI / TOML ────────────────────────────────────────────────────────────
    { foreground: "FFEE44", token: "section" },
    { foreground: "BBEEFF", token: "key" },
    { foreground: "44DD88", token: "value" },

    // ── Operators / delimiters ────────────────────────────────────────────────
    { foreground: "88BBEE", token: "operator" },
    { foreground: "446699", token: "delimiter" },
    { foreground: "446699", token: "delimiter.bracket" },
    { foreground: "446699", token: "delimiter.parenthesis" },
    { foreground: "446699", token: "delimiter.curly" },
    { foreground: "446699", token: "delimiter.square" },
    { foreground: "446699", token: "delimiter.array" },

    // ── Markdown ──────────────────────────────────────────────────────────────
    { foreground: "44EEFF", token: "markup.heading" },
    { foreground: "FFEE44", token: "markup.bold", fontStyle: "bold" },
    { foreground: "44DD88", token: "markup.italic", fontStyle: "italic" },
    { foreground: "88BBFF", token: "markup.underline.link" },
    { foreground: "44DD88", token: "markup.inline.raw" },

    // ── Diff ──────────────────────────────────────────────────────────────────
    { foreground: "FF6666", token: "markup.deleted" },
    { foreground: "44EE88", token: "markup.inserted" },

    // ── Invalid ───────────────────────────────────────────────────────────────
    { foreground: "BBEEFF", background: "881111", token: "invalid" },
    { foreground: "BBEEFF", background: "443388", token: "invalid.deprecated" },
  ],
  colors: {
    "editor.background":                      "#0000A8",
    "editor.foreground":                      "#FFFFFF",
    "editorLineNumber.foreground":            "#5566DD",
    "editorLineNumber.activeForeground":      "#AABBFF",
    "editor.lineHighlightBackground":         "#0808C0",
    "editor.lineHighlightBorder":             "#00000000",
    "editor.selectionBackground":             "#57FFFF50",
    "editor.inactiveSelectionBackground":     "#57FFFF28",
    "editor.selectionHighlightBackground":    "#57FFFF20",
    "editor.wordHighlightBackground":         "#57FFFF20",
    "editor.wordHighlightStrongBackground":   "#57FFFF30",
    "editorCursor.foreground":                "#57FFFF",
    "editorCursor.background":                "#0000A8",
    "editorBracketMatch.background":          "#57FFFF30",
    "editorBracketMatch.border":              "#57FFFF70",
    "editorIndentGuide.background1":          "#1A1ACC",
    "editorIndentGuide.activeBackground1":    "#3344DD",
    "editorRuler.foreground":                 "#1A1ACC",
    "editorWhitespace.foreground":            "#2222CC",
    "editorWidget.background":                "#0000C0",
    "editorWidget.border":                    "#57FFFF",
    "editorWidget.foreground":                "#FFFFFF",
    "editorSuggestWidget.background":         "#0000C0",
    "editorSuggestWidget.border":             "#57FFFF",
    "editorSuggestWidget.foreground":         "#FFFFFF",
    "editorSuggestWidget.selectedBackground": "#0044CC",
    "editorSuggestWidget.highlightForeground":"#57FFFF",
    "editorHoverWidget.background":           "#0000C0",
    "editorHoverWidget.border":               "#57FFFF",
    "editorHoverWidget.foreground":           "#FFFFFF",
    "editorGutter.background":                "#0000A8",
    "editorGutter.addedBackground":           "#22AA44",
    "editorGutter.modifiedBackground":        "#AAAA00",
    "editorGutter.deletedBackground":         "#AA2222",
    "scrollbar.shadow":                       "#00000060",
    "scrollbarSlider.background":             "#57FFFF30",
    "scrollbarSlider.hoverBackground":        "#57FFFF55",
    "scrollbarSlider.activeBackground":       "#57FFFF80",
    "editor.findMatchBackground":             "#57FFFF50",
    "editor.findMatchHighlightBackground":    "#57FFFF28",
    "editor.findMatchBorder":                 "#57FFFF90",
    "editorSelectionHighlightBorder":         "#57FFFF40",
    "input.background":                       "#0000C0",
    "input.border":                           "#57FFFF",
    "input.foreground":                       "#FFFFFF",
    "input.placeholderForeground":            "#8888CC",
    "dropdown.background":                    "#0000C0",
    "dropdown.border":                        "#57FFFF",
    "dropdown.foreground":                    "#FFFFFF",
    "list.hoverBackground":                   "#0808CC",
    "list.activeSelectionBackground":         "#0044CC",
    "list.activeSelectionForeground":         "#FFFFFF",
    "list.inactiveSelectionBackground":       "#0000C0",
    "list.highlightForeground":               "#57FFFF",
    "focusBorder":                            "#3355BB70",
  },
};

// ── Norton Light — NC blueprint: light blue-white paper, navy ink ─────────────
//
// Colour philosophy: "NC document" — imagine the NC UI printed on bright paper.
// Background: pale lavender-blue  |  Text: deep navy  |  Accents: NC blue
// Syntax: keywords=navy, strings=dark-green, numbers=dark-magenta, fn=dark-blue

export const MONACO_THEME_NORTON_LIGHT: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { background: "ECF1FC", token: "" },

    // ── Comments ──────────────────────────────────────────────────────────────
    { foreground: "8899BB", token: "comment", fontStyle: "italic" },
    { foreground: "8899BB", token: "meta.diff" },
    { foreground: "8899BB", token: "meta.diff.header" },

    // ── Strings ───────────────────────────────────────────────────────────────
    { foreground: "005C22", token: "string" },
    { foreground: "005C22", token: "markup.changed" },
    { foreground: "005C22", token: "entity.name.filename.find-in-files" },
    { foreground: "005C22", token: "regexp" },

    // ── Constants / numbers ───────────────────────────────────────────────────
    { foreground: "880066", token: "constant.numeric" },
    { foreground: "880066", token: "constant.language" },
    { foreground: "880066", token: "constant.character" },
    { foreground: "880066", token: "constant.other" },
    { foreground: "880066", token: "number" },
    { foreground: "880066", token: "number.float" },
    { foreground: "880066", token: "number.hex" },

    // ── Keywords / storage ────────────────────────────────────────────────────
    { foreground: "0000AA", token: "keyword" },
    { foreground: "0000AA", token: "storage" },

    // ── Types / support ───────────────────────────────────────────────────────
    { foreground: "005577", token: "storage.type", fontStyle: "italic" },
    { foreground: "005577", token: "support.function" },
    { foreground: "005577", token: "support.constant" },
    { foreground: "005577", token: "support.type", fontStyle: "italic" },
    { foreground: "005577", token: "support.class", fontStyle: "italic" },
    { foreground: "005577", token: "type" },
    { foreground: "005577", token: "type.identifier" },
    { foreground: "005577", token: "class" },

    // ── Functions / identifiers ───────────────────────────────────────────────
    { foreground: "0033AA", token: "entity.name.class", fontStyle: "underline" },
    { foreground: "0033AA", token: "entity.other.inherited-class", fontStyle: "italic underline" },
    { foreground: "0033AA", token: "entity.name.function" },
    { foreground: "0033AA", token: "function" },
    { foreground: "0033AA", token: "function.name" },

    // ── Parameters / variables ────────────────────────────────────────────────
    { foreground: "2244AA", token: "variable.parameter", fontStyle: "italic" },
    { foreground: "2A2A88", token: "variable" },
    { foreground: "060650", token: "identifier" },

    // ── XML / HTML ────────────────────────────────────────────────────────────
    { foreground: "8B0000", token: "entity.name.tag" },
    { foreground: "005588", token: "entity.other.attribute-name" },
    { foreground: "8B0000", token: "meta.tag" },
    { foreground: "8B0000", token: "tag" },
    { foreground: "005588", token: "attribute.name" },
    { foreground: "005C22", token: "attribute.value" },
    { foreground: "8899BB", token: "metatag" },
    { foreground: "8899BB", token: "metatag.content", fontStyle: "italic" },

    // ── CSS / SCSS ────────────────────────────────────────────────────────────
    { foreground: "8B0000", token: "selector" },
    { foreground: "8B0000", token: "selector.tag" },
    { foreground: "005588", token: "selector.class" },
    { foreground: "005588", token: "selector.id" },
    { foreground: "005C22", token: "property.css" },
    { foreground: "005C22", token: "property" },
    { foreground: "880066", token: "unit" },
    { foreground: "005577", token: "pseudo" },
    { foreground: "CC0000", token: "important" },

    // ── INI / TOML ────────────────────────────────────────────────────────────
    { foreground: "0000AA", token: "section" },
    { foreground: "060650", token: "key" },
    { foreground: "005C22", token: "value" },

    // ── Operators / delimiters ────────────────────────────────────────────────
    { foreground: "334499", token: "operator" },
    { foreground: "7788AA", token: "delimiter" },
    { foreground: "7788AA", token: "delimiter.bracket" },
    { foreground: "7788AA", token: "delimiter.parenthesis" },
    { foreground: "7788AA", token: "delimiter.curly" },
    { foreground: "7788AA", token: "delimiter.square" },
    { foreground: "7788AA", token: "delimiter.array" },

    // ── Markdown ──────────────────────────────────────────────────────────────
    { foreground: "0033AA", token: "markup.heading" },
    { foreground: "0000AA", token: "markup.bold", fontStyle: "bold" },
    { foreground: "005C22", token: "markup.italic", fontStyle: "italic" },
    { foreground: "005577", token: "markup.underline.link" },
    { foreground: "005C22", token: "markup.inline.raw" },

    // ── Diff ──────────────────────────────────────────────────────────────────
    { foreground: "AA1111", token: "markup.deleted" },
    { foreground: "117711", token: "markup.inserted" },

    // ── Invalid ───────────────────────────────────────────────────────────────
    { foreground: "FFFFFF", background: "CC1111", token: "invalid" },
    { foreground: "FFFFFF", background: "884488", token: "invalid.deprecated" },
  ],
  colors: {
    "editor.background":                      "#ECF1FC",
    "editor.foreground":                      "#060650",
    "editorLineNumber.foreground":            "#AABBDD",
    "editorLineNumber.activeForeground":      "#4455AA",
    "editor.lineHighlightBackground":         "#E4EBF9",
    "editor.lineHighlightBorder":             "#00000000",
    "editor.selectionBackground":             "#BBCCEE99",
    "editor.inactiveSelectionBackground":     "#BBCCEE55",
    "editor.selectionHighlightBackground":    "#BBCCEE44",
    "editor.wordHighlightBackground":         "#BBCCEE44",
    "editor.wordHighlightStrongBackground":   "#AABCDD44",
    "editorCursor.foreground":                "#0000CC",
    "editorCursor.background":                "#ECF1FC",
    "editorBracketMatch.background":          "#BBCCEE60",
    "editorBracketMatch.border":              "#8899CC70",
    "editorIndentGuide.background1":          "#D8E2F5",
    "editorIndentGuide.activeBackground1":    "#BBCCEE",
    "editorRuler.foreground":                 "#D8E2F5",
    "editorWhitespace.foreground":            "#CCd8F0",
    "editorWidget.background":                "#E8EFFA",
    "editorWidget.border":                    "#8899CC",
    "editorWidget.foreground":                "#060650",
    "editorSuggestWidget.background":         "#E8EFFA",
    "editorSuggestWidget.border":             "#8899CC",
    "editorSuggestWidget.foreground":         "#060650",
    "editorSuggestWidget.selectedBackground": "#BBCCEE",
    "editorSuggestWidget.highlightForeground":"#0000AA",
    "editorHoverWidget.background":           "#E8EFFA",
    "editorHoverWidget.border":               "#8899CC",
    "editorHoverWidget.foreground":           "#060650",
    "editorGutter.background":                "#ECF1FC",
    "editorGutter.addedBackground":           "#228844",
    "editorGutter.modifiedBackground":        "#886611",
    "editorGutter.deletedBackground":         "#AA2222",
    "scrollbar.shadow":                       "#00000015",
    "scrollbarSlider.background":             "#8899CC44",
    "scrollbarSlider.hoverBackground":        "#7788BB77",
    "scrollbarSlider.activeBackground":       "#5566AA99",
    "editor.findMatchBackground":             "#BBCCEE80",
    "editor.findMatchHighlightBackground":    "#BBCCEE50",
    "editor.findMatchBorder":                 "#7799CC80",
    "editorSelectionHighlightBorder":         "#BBCCEE60",
    "input.background":                       "#EEF3FD",
    "input.border":                           "#8899CC",
    "input.foreground":                       "#060650",
    "input.placeholderForeground":            "#8899BB",
    "dropdown.background":                    "#E8EFFA",
    "dropdown.border":                        "#8899CC",
    "dropdown.foreground":                    "#060650",
    "list.hoverBackground":                   "#E0E9F8",
    "list.activeSelectionBackground":         "#BBCCEE",
    "list.activeSelectionForeground":         "#060650",
    "list.inactiveSelectionBackground":       "#CCDBF2",
    "list.highlightForeground":               "#0000AA",
    "focusBorder":                            "#7788CC70",
  },
};

// ── Monokai Dark ──────────────────────────────────────────────────────────────
export const MONACO_THEME_MONOKAI_DARK: Monaco.editor.IStandaloneThemeData = {
  base: "vs-dark",
  inherit: true,
  rules: [
    { background: "272822", token: "" },
    { foreground: "75715e", token: "comment", fontStyle: "italic" },
    { foreground: "75715e", token: "punctuation.definition.comment" },
    { foreground: "e6db74", token: "string" },
    { foreground: "e6db74", token: "constant.other.symbol" },
    { foreground: "ae81ff", token: "constant.numeric" },
    { foreground: "ae81ff", token: "constant.language" },
    { foreground: "ae81ff", token: "number" },
    { foreground: "ae81ff", token: "number.float" },
    { foreground: "ae81ff", token: "number.hex" },
    { foreground: "f92672", token: "keyword" },
    { foreground: "f92672", token: "storage" },
    { foreground: "f92672", token: "keyword.control" },
    { foreground: "f92672", token: "keyword.other" },
    { foreground: "f92672", token: "entity.name.tag" },
    { foreground: "f92672", token: "tag" },
    { foreground: "a6e22e", token: "entity.name.function" },
    { foreground: "a6e22e", token: "support.function" },
    { foreground: "a6e22e", token: "function" },
    { foreground: "a6e22e", token: "function.name" },
    { foreground: "a6e22e", token: "markup.heading" },
    { foreground: "66d9ef", token: "storage.type", fontStyle: "italic" },
    { foreground: "66d9ef", token: "support.type", fontStyle: "italic" },
    { foreground: "66d9ef", token: "support.class", fontStyle: "italic" },
    { foreground: "66d9ef", token: "type" },
    { foreground: "66d9ef", token: "type.identifier" },
    { foreground: "66d9ef", token: "class" },
    { foreground: "fd971f", token: "variable", fontStyle: "italic" },
    { foreground: "fd971f", token: "variable.parameter", fontStyle: "italic" },
    { foreground: "fd971f", token: "identifier" },
    { foreground: "f8f8f2", token: "operator" },
    { foreground: "75715e", token: "delimiter" },
    { foreground: "f8f8f2", token: "delimiter.parenthesis" },
    { foreground: "f8f8f2", token: "delimiter.bracket" },
    { foreground: "e6db74", token: "attribute.value" },
    { foreground: "a6e22e", token: "attribute.name" },
    { foreground: "f92672", token: "selector" },
    { foreground: "ae81ff", token: "constant" },
    { foreground: "e6db74", token: "regexp" },
    { foreground: "66d9ef", token: "keyword.plc" },    // PLC IF/WHILE/OPEN
    { foreground: "a6e22e", token: "support.function.plc" }, // PLC @ macros
  ],
  colors: {
    "editor.background": "#272822",
    "editor.foreground": "#f8f8f2",
    "editorLineNumber.foreground": "#49483e",
    "editorLineNumber.activeForeground": "#a59f85",
    "editor.lineHighlightBackground": "#3e3d32",
    "editor.lineHighlightBorder": "#00000000",
    "editor.selectionBackground": "#49483e",
    "editor.inactiveSelectionBackground": "#3e3d3280",
    "editor.selectionHighlightBackground": "#49483e60",
    "editor.wordHighlightBackground": "#49483e60",
    "editorCursor.foreground": "#f8f8f0",
    "editorCursor.background": "#272822",
    "editorBracketMatch.background": "#49483e80",
    "editorBracketMatch.border": "#75715e60",
    "editorWidget.background": "#1e1f1c",
    "editorWidget.border": "#75715e",
    "editorWidget.foreground": "#f8f8f2",
    "editorSuggestWidget.background": "#1e1f1c",
    "editorSuggestWidget.border": "#75715e",
    "editorSuggestWidget.foreground": "#f8f8f2",
    "editorSuggestWidget.selectedBackground": "#49483e",
    "editorSuggestWidget.highlightForeground": "#a6e22e",
    "editorHoverWidget.background": "#1e1f1c",
    "editorHoverWidget.border": "#75715e",
    "editorHoverWidget.foreground": "#f8f8f2",
    "editorGutter.background": "#272822",
    "input.background": "#1e1f1c",
    "input.border": "#75715e",
    "input.foreground": "#f8f8f2",
    "input.placeholderForeground": "#75715e",
    "dropdown.background": "#1e1f1c",
    "dropdown.border": "#75715e",
    "dropdown.foreground": "#f8f8f2",
    "scrollbar.shadow": "#00000060",
    "scrollbarSlider.background": "#49483e60",
    "scrollbarSlider.hoverBackground": "#75715e80",
    "scrollbarSlider.activeBackground": "#75715e90",
    "editor.findMatchBackground": "#ffe79260",
    "editor.findMatchHighlightBackground": "#ffe79230",
  },
};

// ── Monokai Light — transposed Monokai palette on warm white ─────────────────
export const MONACO_THEME_MONOKAI_LIGHT: Monaco.editor.IStandaloneThemeData = {
  base: "vs",
  inherit: true,
  rules: [
    { background: "fffff8", token: "" },
    { foreground: "8a8a72", token: "comment", fontStyle: "italic" },
    { foreground: "8a8a72", token: "punctuation.definition.comment" },
    { foreground: "5a5a00", token: "string" },
    { foreground: "6e35a0", token: "constant.numeric" },
    { foreground: "6e35a0", token: "constant.language" },
    { foreground: "6e35a0", token: "number" },
    { foreground: "6e35a0", token: "number.float" },
    { foreground: "6e35a0", token: "number.hex" },
    { foreground: "c0002a", token: "keyword" },
    { foreground: "c0002a", token: "storage" },
    { foreground: "c0002a", token: "keyword.control" },
    { foreground: "c0002a", token: "keyword.other" },
    { foreground: "c0002a", token: "entity.name.tag" },
    { foreground: "c0002a", token: "tag" },
    { foreground: "3a7500", token: "entity.name.function" },
    { foreground: "3a7500", token: "support.function" },
    { foreground: "3a7500", token: "function" },
    { foreground: "3a7500", token: "function.name" },
    { foreground: "006080", token: "storage.type", fontStyle: "italic" },
    { foreground: "006080", token: "support.type", fontStyle: "italic" },
    { foreground: "006080", token: "support.class", fontStyle: "italic" },
    { foreground: "006080", token: "type" },
    { foreground: "006080", token: "type.identifier" },
    { foreground: "006080", token: "class" },
    { foreground: "905000", token: "variable", fontStyle: "italic" },
    { foreground: "905000", token: "variable.parameter", fontStyle: "italic" },
    { foreground: "272822", token: "identifier" },
    { foreground: "272822", token: "operator" },
    { foreground: "aaaaaa", token: "delimiter" },
    { foreground: "272822", token: "delimiter.parenthesis" },
    { foreground: "272822", token: "delimiter.bracket" },
    { foreground: "5a5a00", token: "attribute.value" },
    { foreground: "3a7500", token: "attribute.name" },
    { foreground: "c0002a", token: "selector" },
    { foreground: "6e35a0", token: "constant" },
    { foreground: "5a5a00", token: "regexp" },
    { foreground: "c0002a", token: "keyword.plc" },
    { foreground: "3a7500", token: "support.function.plc" },
  ],
  colors: {
    "editor.background": "#fffff8",
    "editor.foreground": "#272822",
    "editorLineNumber.foreground": "#ccccc0",
    "editorLineNumber.activeForeground": "#8a8a72",
    "editor.lineHighlightBackground": "#f5f5e8",
    "editor.lineHighlightBorder": "#00000000",
    "editor.selectionBackground": "#d6d6c4",
    "editor.inactiveSelectionBackground": "#e8e8d880",
    "editor.selectionHighlightBackground": "#d6d6c460",
    "editor.wordHighlightBackground": "#d6d6c460",
    "editorCursor.foreground": "#272822",
    "editorCursor.background": "#fffff8",
    "editorBracketMatch.background": "#d6d6c480",
    "editorBracketMatch.border": "#aaaaaa60",
    "editorWidget.background": "#f0f0e8",
    "editorWidget.border": "#ccccaa",
    "editorWidget.foreground": "#272822",
    "editorSuggestWidget.background": "#f0f0e8",
    "editorSuggestWidget.border": "#ccccaa",
    "editorSuggestWidget.foreground": "#272822",
    "editorSuggestWidget.selectedBackground": "#d6d6c4",
    "editorSuggestWidget.highlightForeground": "#3a7500",
    "editorHoverWidget.background": "#f0f0e8",
    "editorHoverWidget.border": "#ccccaa",
    "editorHoverWidget.foreground": "#272822",
    "editorGutter.background": "#fffff8",
    "input.background": "#f0f0e8",
    "input.border": "#ccccaa",
    "input.foreground": "#272822",
    "input.placeholderForeground": "#aaaaaa",
    "dropdown.background": "#f0f0e8",
    "dropdown.border": "#ccccaa",
    "dropdown.foreground": "#272822",
    "scrollbar.shadow": "#00000020",
    "scrollbarSlider.background": "#ccccaa60",
    "scrollbarSlider.hoverBackground": "#aaaaaa80",
    "scrollbarSlider.activeBackground": "#aaaaaa90",
    "editor.findMatchBackground": "#ffe79280",
    "editor.findMatchHighlightBackground": "#ffe79240",
  },
};
